---
domain: "www.zootracker.app"
web_root: "/var/www/zootracker"
app_upstream: "http://127.0.0.1:8000"
cloudflare_api_token: "{{ vault_cloudflare_api_token | default('') }}"
s3_endpoint: "nbg1.your-objectstorage.com"
s3_bucket: "zootracker-public-images"
